/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVerifyRouteImport } from './routes/_app.verify'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppScansRouteImport } from './routes/_app.scans'
import { Route as AppRenewalsRouteImport } from './routes/_app.renewals'
import { Route as AppPermitsRouteImport } from './routes/_app.permits'
import { Route as AppPermitHolderRouteImport } from './routes/_app.permit-holder'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppIssueRouteImport } from './routes/_app.issue'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppScansRoute = AppScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AppRoute,
} as any)
const AppRenewalsRoute = AppRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsRoute = AppPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitHolderRoute = AppPermitHolderRouteImport.update({
  id: '/permit-holder',
  path: '/permit-holder',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppIssueRoute = AppIssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AppAlertsRoute
  '/issue': typeof AppIssueRoute
  '/overview': typeof AppOverviewRoute
  '/permit-holder': typeof AppPermitHolderRoute
  '/permits': typeof AppPermitsRoute
  '/renewals': typeof AppRenewalsRoute
  '/scans': typeof AppScansRoute
  '/users': typeof AppUsersRoute
  '/verify': typeof AppVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AppAlertsRoute
  '/issue': typeof AppIssueRoute
  '/overview': typeof AppOverviewRoute
  '/permit-holder': typeof AppPermitHolderRoute
  '/permits': typeof AppPermitsRoute
  '/renewals': typeof AppRenewalsRoute
  '/scans': typeof AppScansRoute
  '/users': typeof AppUsersRoute
  '/verify': typeof AppVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/issue': typeof AppIssueRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/permit-holder': typeof AppPermitHolderRoute
  '/_app/permits': typeof AppPermitsRoute
  '/_app/renewals': typeof AppRenewalsRoute
  '/_app/scans': typeof AppScansRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/verify': typeof AppVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/alerts'
    | '/issue'
    | '/overview'
    | '/permit-holder'
    | '/permits'
    | '/renewals'
    | '/scans'
    | '/users'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/alerts'
    | '/issue'
    | '/overview'
    | '/permit-holder'
    | '/permits'
    | '/renewals'
    | '/scans'
    | '/users'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/access-denied'
    | '/auth'
    | '/_app/alerts'
    | '/_app/issue'
    | '/_app/overview'
    | '/_app/permit-holder'
    | '/_app/permits'
    | '/_app/renewals'
    | '/_app/scans'
    | '/_app/users'
    | '/_app/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/verify': {
      id: '/_app/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scans': {
      id: '/_app/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof AppScansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/renewals': {
      id: '/_app/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AppRenewalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits': {
      id: '/_app/permits'
      path: '/permits'
      fullPath: '/permits'
      preLoaderRoute: typeof AppPermitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permit-holder': {
      id: '/_app/permit-holder'
      path: '/permit-holder'
      fullPath: '/permit-holder'
      preLoaderRoute: typeof AppPermitHolderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issue': {
      id: '/_app/issue'
      path: '/issue'
      fullPath: '/issue'
      preLoaderRoute: typeof AppIssueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppIssueRoute: typeof AppIssueRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPermitHolderRoute: typeof AppPermitHolderRoute
  AppPermitsRoute: typeof AppPermitsRoute
  AppRenewalsRoute: typeof AppRenewalsRoute
  AppScansRoute: typeof AppScansRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVerifyRoute: typeof AppVerifyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppIssueRoute: AppIssueRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPermitHolderRoute: AppPermitHolderRoute,
  AppPermitsRoute: AppPermitsRoute,
  AppRenewalsRoute: AppRenewalsRoute,
  AppScansRoute: AppScansRoute,
  AppUsersRoute: AppUsersRoute,
  AppVerifyRoute: AppVerifyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
